version: '3.8'

services:

  ads-report-redis:
    image: redis:latest
    container_name: ads-report-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ads-report-network
    command: ["redis-server", "--appendonly", "yes"]

  ads-report-backend:
    build:
      context: ../back-end/report
      dockerfile: Dockerfile
    image: report-app:latest
    container_name: ads-report-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: ads-report-redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 12h
    networks:
      - ads-report-network
    depends_on:
      - ads-report-redis

networks:
  ads-report-network: 
    driver: bridge

volumes:
  redis-data:
    driver: local
