version: '3.8'

services:
  report-app:
    build:
      context: ../back-end/report
      dockerfile: Dockerfile
    image: report-app:latest
    container_name: report-backend
    ports:
      - "8080:8080"
    networks:
      - report-network
    ## For production, is recomended to set the volumes for the properties of the app.
    ## For development you can comment the volumes bellow.
    volumes:
      - ./src/main/resources/ads.properties:/app/resources/ads.properties
      - ./src/main/resources/credentials.json:/app/resources/credentials.json

networks:
  report-network: 
    driver: bridge
